apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-go2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-go2 
  name: test-go2
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: test-go2 
